### PR TITLE
GameTypeNames

### PR DESCRIPTION
**Pull request by OwnedTom**
Added the ability to choose GameType by name

### CODE REVIEW

**Comment by DEElekgolo** [comment]
Something we were going to do but glad to see you hop onto it. Would be nice if the names were next to the enum found in [BlamTypes.h](https://github.com/DEElekgolo/ElDorito/blob/master/BlamTypes.h) though rather than coupled with the module. Eventually I plan to add overall case insensitivity to stuff like this.

**Comment by emoose** [comment]
>Your IDE seems to have added spaces next to every if statement. going from if( blah ) to if (blah)

Which is how it should be, and also how VS is configured by default, so we're probably going to get a lot of that :+1:

**Comment by OwnedTom** [comment]
Also, new build makes arguments case insensitive

**Comment by JakeShirley** [comment]
Why did this get closed, this is a good feature!

**Pull request closed without merging**
